version: 2
updates:
- package-ecosystem: "cargo"
  # Look for `Cargo.toml` and `Cargo.lock` in the root directory
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
